import { useState, useEffect, type ReactNode } from 'react';
import { useQuery, useQueryClient } from '@tanstack/react-query';
import { LockKeyhole } from 'lucide-react';
import { viewerApi } from './viewer-access';
export function MembershipGate({children}:{children:ReactNode}) {
 const q=useQuery<{membership:{plan:string;expires:string}|null;telegram:string;plans:{id:string;price:number;enabled:boolean}[]}>({queryKey:['member-access'],queryFn:()=>viewerApi('registration/membership'),refetchInterval:10000,retry:false});
 const client=useQueryClient();const [message,setMessage]=useState('');
 useEffect(()=>{if(q.data?.membership)void client.invalidateQueries({queryKey:['/api/registration/me']});},[q.data?.membership?.expires,client]);
 if(q.isLoading)return <p className="p-12 text-center">Checking membership…</p>;
 if(q.isError||!q.data)return <div className="p-12 text-center"><p>Could not check your membership.</p><button onClick={()=>q.refetch()} className="mt-4 text-accent">Try again</button></div>;
 if(q.data.membership)return <>{children}</>;
 return <div className="mx-auto max-w-5xl px-5 py-12"><div className="relative overflow-hidden rounded-3xl border border-accent/25 bg-card">
 <div aria-hidden="true" className="pointer-events-none absolute inset-0 select-none p-8 opacity-25 blur-sm"><h2 className="font-editorial text-4xl">Complete your profile</h2><div className="mt-8 grid gap-6 sm:grid-cols-2">{['About you','Location','Photos','Preferences','Review and publish'].map(x=><div key={x} className="h-28 rounded-xl border border-white/20 bg-white/5 p-5">{x}</div>)}</div></div>
 <div className="relative bg-black/65 px-5 py-10 text-center backdrop-blur-sm sm:px-10"><LockKeyhole className="mx-auto text-accent" size={38}/><p className="mt-4 text-xs uppercase tracking-[.2em] text-accent">Your account is approved</p><h1 className="mt-4 font-editorial text-4xl sm:text-5xl">Be the man she wants to meet.</h1><p className="mx-auto mt-5 max-w-xl text-sm leading-7 text-muted-foreground">To complete your profile and submit it for the website’s search listings, upgrade to Quarterly or Annual. After payment confirmation, the remaining profile steps will unlock.</p>
 <div className="membership-photo-strip relative mt-8 overflow-hidden rounded-xl" aria-hidden="true"><div className="membership-photo-track flex w-max">{[0,1].map(copy => <div key={copy} className="flex shrink-0 gap-4 pr-4">{Array.from({length:10},(_,index) => <img key={index} src={`/assets/upgrade-women/woman-${String(index + 1).padStart(2,'0')}.jpeg`} alt="" width={180} height={240} draggable={false} className="h-56 w-40 shrink-0 rounded-xl bg-black/30 object-contain sm:h-64 sm:w-48" />)}</div>)}</div><div className="pointer-events-none absolute inset-0 bg-gradient-to-r from-black/40 via-transparent to-black/40"/></div>
 <p className="mx-auto mt-6 max-w-xl text-sm leading-6 text-muted-foreground">Choose Quarterly or Annual to unlock profile completion after payment confirmation. Once your completed profile is approved, women can discover you and send interest.</p><div className="mt-7 grid gap-5 sm:grid-cols-2">{q.data.plans.filter(p=>p.enabled).map(p=><div key={p.id} className="rounded-2xl border border-accent/35 bg-background/90 p-6"><h2 className="font-editorial text-3xl">{p.id==='quarterly'?'Quarterly':'Annual'}</h2><p className="mt-2 text-sm text-muted-foreground">{p.id==='quarterly'?'3 months':'12 months'}</p><p className="my-5 text-4xl text-accent">₹{p.price.toLocaleString('en-IN')}</p>{q.data!.telegram?<a className="block rounded-full bg-primary px-6 py-3 text-sm font-semibold text-white" href={`https://t.me/${q.data!.telegram}`} target="_blank" rel="noreferrer" onClick={()=>{void viewerApi('registration/boosts',{plan:p.id}).then(()=>{setMessage('Your payment request is saved. Complete payment with our team on Telegram.');client.invalidateQueries({queryKey:['member-boosts']});}).catch(e=>setMessage((e as Error).message));}}>Pay Now · Continue on Telegram</a>:<p className="text-sm text-muted-foreground">Payment contact will be available shortly.</p>}</div>)}</div><p role="status" className="mt-4 text-sm text-accent">{message}</p><p className="mt-5 text-xs text-muted-foreground">Pay Now opens our team’s Telegram. Access unlocks after admin confirms payment; completed profiles still require review.</p><button className="mt-4 text-sm text-accent underline" onClick={()=>q.refetch()}>Payment confirmed? Check access</button>
 </div></div></div>;
}
export function PaymentSettings(){
 const q=useQuery<{telegram:string}>({queryKey:['payment-settings'],queryFn:()=>viewerApi('registration/admin/payment-settings')});
 const [value,setValue]=useState<string|null>(null);const [message,setMessage]=useState('');const [busy,setBusy]=useState(false);
 return <form className="mt-6 rounded-2xl border border-foreground/15 p-6" onSubmit={async e=>{e.preventDefault();setBusy(true);try{await viewerApi('registration/admin/payment-settings',{telegram:value??q.data?.telegram??''});await q.refetch();setMessage('Payment Telegram account saved.');}catch(e){setMessage((e as Error).message);}finally{setBusy(false);}}}><h2 className="font-editorial text-2xl">Pay Now Telegram account</h2><label className="mt-4 block text-sm">Telegram username or link<input required className="mt-2 w-full rounded-xl border border-foreground/20 bg-background p-3" value={value??q.data?.telegram??''} placeholder="@your_username" onChange={e=>setValue(e.target.value)}/></label><button disabled={busy||q.isLoading||q.isError} className="mt-4 rounded-full bg-primary px-5 py-3">Save payment contact</button><p role="status" className="mt-3 text-sm">{q.isError?'Could not load payment settings.':message}</p></form>;
}
