// Idempotent schema for Neon/PostgreSQL. Used by API startup and the legacy import.
export const registrationSchemaSql = `
CREATE TABLE IF NOT EXISTS viewers (
 id TEXT PRIMARY KEY, contact TEXT UNIQUE NOT NULL, password TEXT NOT NULL,
 record JSONB NOT NULL
);
CREATE TABLE IF NOT EXISTS viewer_sessions (
 token TEXT PRIMARY KEY, member TEXT NOT NULL REFERENCES viewers(id) ON DELETE CASCADE,
 expires BIGINT NOT NULL
);
CREATE TABLE IF NOT EXISTS registrations (
  id TEXT PRIMARY KEY,
  public_id BIGINT GENERATED BY DEFAULT AS IDENTITY UNIQUE,
  email TEXT UNIQUE NOT NULL,
  mobile TEXT UNIQUE NOT NULL,
  password TEXT NOT NULL,
  record JSONB NOT NULL
);
CREATE TABLE IF NOT EXISTS registration_sessions (
  token TEXT PRIMARY KEY,
  member TEXT NOT NULL REFERENCES registrations(id) ON DELETE CASCADE,
  expires BIGINT NOT NULL
);
CREATE INDEX IF NOT EXISTS registration_sessions_expires_idx ON registration_sessions(expires);
CREATE TABLE IF NOT EXISTS registration_settings (id INTEGER PRIMARY KEY, value JSONB NOT NULL);
CREATE TABLE IF NOT EXISTS registration_admin_sessions (token TEXT PRIMARY KEY, expires BIGINT NOT NULL);
CREATE INDEX IF NOT EXISTS registration_admin_sessions_expires_idx ON registration_admin_sessions(expires);
CREATE TABLE IF NOT EXISTS member_interests (
 id TEXT PRIMARY KEY, viewer_id TEXT NOT NULL REFERENCES viewers(id) ON DELETE CASCADE,
 profile_id BIGINT NOT NULL, profile_slug TEXT NOT NULL, profile_name TEXT NOT NULL,
 note TEXT NOT NULL, created_at TIMESTAMPTZ NOT NULL DEFAULT now(), delivery TEXT NOT NULL DEFAULT 'Pending'
);
CREATE TABLE IF NOT EXISTS profile_boosts (
 id TEXT PRIMARY KEY, member TEXT NOT NULL REFERENCES registrations(id) ON DELETE CASCADE,
 plan TEXT NOT NULL, price NUMERIC NOT NULL, status TEXT NOT NULL DEFAULT 'Pending',
 created_at TIMESTAMPTZ NOT NULL DEFAULT now(), expires TIMESTAMPTZ
);
CREATE UNIQUE INDEX IF NOT EXISTS profile_boosts_pending_idx ON profile_boosts(member) WHERE status = 'Pending';
CREATE INDEX IF NOT EXISTS member_interests_viewer_idx ON member_interests(viewer_id, created_at DESC);
CREATE INDEX IF NOT EXISTS member_interests_profile_idx ON member_interests(profile_slug, created_at DESC);
CREATE INDEX IF NOT EXISTS profile_boosts_member_idx ON profile_boosts(member);
UPDATE registration_settings
SET value = value || '{"plans":[{"id":"quarterly","price":499,"enabled":true},{"id":"yearly","price":999,"enabled":true}],"pricingVersion":"quarterly-yearly-v1"}'::jsonb
WHERE id = 1 AND NOT EXISTS (SELECT 1 FROM jsonb_array_elements(value->'plans') AS plan WHERE plan->>'id' = 'yearly');
CREATE TABLE IF NOT EXISTS discovery_settings (id INTEGER PRIMARY KEY, value JSONB NOT NULL);
CREATE TABLE IF NOT EXISTS seo_settings (id INTEGER PRIMARY KEY, site_url TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS seo_pages (path TEXT PRIMARY KEY, title TEXT NOT NULL, description TEXT NOT NULL, canonical TEXT NOT NULL DEFAULT '', noindex BOOLEAN NOT NULL DEFAULT false);
CREATE TABLE IF NOT EXISTS seo_verification_files (filename TEXT PRIMARY KEY, content TEXT NOT NULL, uploaded_at TIMESTAMPTZ NOT NULL DEFAULT now());
UPDATE registration_settings SET value = jsonb_set(value, '{plans}', (
 SELECT jsonb_agg(CASE WHEN plan->>'id' = 'halfyearly' THEN jsonb_set(plan, '{id}', '"quarterly"') ELSE plan END)
 FROM jsonb_array_elements(value->'plans') AS plan
)) WHERE id=1 AND EXISTS (SELECT 1 FROM jsonb_array_elements(value->'plans') AS plan WHERE plan->>'id'='halfyearly');
CREATE TABLE IF NOT EXISTS membership_payment_settings (id INTEGER PRIMARY KEY, username TEXT NOT NULL);
`;
