// Idempotent schema for Neon/PostgreSQL. Used by API startup and the legacy import.
export const registrationSchemaSql = `
CREATE TABLE IF NOT EXISTS registrations (
  id TEXT PRIMARY KEY,
  public_id BIGINT GENERATED BY DEFAULT AS IDENTITY UNIQUE,
  email TEXT UNIQUE NOT NULL,
  mobile TEXT UNIQUE NOT NULL,
  password TEXT NOT NULL,
  record JSONB NOT NULL
);
CREATE TABLE IF NOT EXISTS registration_sessions (
  token TEXT PRIMARY KEY,
  member TEXT NOT NULL REFERENCES registrations(id) ON DELETE CASCADE,
  expires BIGINT NOT NULL
);
CREATE INDEX IF NOT EXISTS registration_sessions_expires_idx ON registration_sessions(expires);
CREATE TABLE IF NOT EXISTS registration_settings (id INTEGER PRIMARY KEY, value JSONB NOT NULL);
CREATE TABLE IF NOT EXISTS registration_admin_sessions (token TEXT PRIMARY KEY, expires BIGINT NOT NULL);
CREATE INDEX IF NOT EXISTS registration_admin_sessions_expires_idx ON registration_admin_sessions(expires);
`;
